# Uncomment the next line to define a global platform for your project
platform :ios, '11.1'

target 'CleanerKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CleanerKit
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  target 'CleanerKitTests' do
    # Pods for testing
  end

end
